### ISSUE TITLE
TODO Task

### ISSUE THREAD

**Issue by randspace0** [andraantariksa/cit207-polygon-paint#1]
- [x] Draw a polygon on the screen. The user can choose to draw a hollow or filled polygon.
- [x] The user can draw multiple polygons; the program must be able to store the data of multiple polygons.
- [x] Delete a polygon.
- [x] Toggle the filled/hollow properties of a polygon.
- [x] Change the color of a polygon.
- [x] Set the priority of a polygon (front/behind).
- [x] Edit/delete a point of a polygon on the screen.
- [x] Save/load data of polygons to/from a file.

**Comment by randspace0** [comment]
Done
